@startuml
left to right direction
skinparam packageStyle rectangle

actor "Usuário" as Usuario
actor  Aluno
actor  Professor
actor "Instituição" as Instituicao
actor "Sistema de email" as Sistema_de_email
actor Empresas

rectangle "Sistema de Moeda Estudantil" {
    usecase "Gerenciar login" as UC01 
    usecase "Selecionar instituição" as UC02 
    usecase "Enviar moedas" as UC03 
    usecase "Notificar Aluno" as UC04 
    usecase "Trocar Moedas" as UC05
}
@enduml