@startuml
left to right direction
skinparam packageStyle rectangle

actor "Sistema de email" as Sistema_de_email
actor "Usuário" as Usuario
actor  Aluno
actor  Professor
actor  Empresa
actor "Instituição" as Instituicao

Aluno --|> Usuario
Professor --|> Usuario
Empresa --|> Usuario

rectangle "Sistema de Moeda Estudantil" {
    usecase "Gerenciar login" as UC01 
    usecase "Selecionar instituição" as UC02 
    usecase "Selecionar vantagem" as UC03 
    usecase "Enviar moedas" as UC04
    usecase "Notificar Aluno" as UC05 
    usecase "Trocar Moedas" as UC06
    usecase "Informar motivo do envio de moedas" as UC07
    usecase "Consultar extrato da conta" as UC08
    usecase "Informar lista de professores" as UC09
    usecase "Cadastrar conta" as UC10
    usecase "Cadastrar vantagens" as UC11
}

Usuario --> UC01
Usuario --> UC08

Aluno --> UC02
Aluno --> UC03
Aluno --> UC06
Aluno --> UC07

Professor --> UC04
Professor --> UC07

Sistema_de_email --> UC05

UC05 --> Aluno

Instituicao --> UC09

Empresa --> UC10
Empresa --> UC11
@enduml